eval_args:
  _target_: roboverse_learn.il.utils.eval_args.Args
  # random:
    # _target_: metasim.cfg.randomization.RandomizationCfg
    # level: 0
  task: ""
  max_step: 200
  num_envs: 1
  sim: "isaacsim"

policy_runner:
  action:
    action_type: "ee"
    ee_cfg:
      rotation_rep: "quaternion"
      gripper_rep: "q_pos"
    delta: False
  obs:
    obs_type: "ee"
    ee_cfg:
      rotation_rep: "quaternion"
      gripper_rep: "q_pos"
