defaults:
  - _self_
  - dataset_config: robot_image_dataset
  - policy_config: ${oc.env:policy_name,ddpm_dit}
  - eval_config: default_eval
  - train_config: default_train

policy_name: ${oc.env:policy_name,ddpm_dit}
task_name: placeholder
name: robot_${task_name}
_target_: roboverse_learn.il.runners.default_runner.DefaultRunner


image_shape: &image_shape [3, 256, 256]
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    head_cam:
      shape: *image_shape
      type: rgb
    agent_pos:
      shape: [9]
      type: low_dim
  action:
    shape: [9]

exp_name: "default"

horizon: 8
n_obs_steps: 3
n_action_steps: 4
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_global_cond: True

train_enable: null
eval_enable: null
eval_path: null

multi_run:
  run_dir: ./il_outputs/${policy_name}/${task_name}
  wandb_name_base: ${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: ./il_outputs/${policy_name}/${task_name}
  sweep:
    dir: ./il_outputs/${policy_name}/${task_name}
    subdir: ${hydra.job.num}

logging:
  project: RoboVerse_IL_${task_name}
  resume: False
  mode: online
  name: ${task_name}
  tags:
    - ${task_name}
    - ${policy_name}
    - ${exp_name}
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 5
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False
  save_root_dir: ./il_outputs/${policy_name}/${task_name}
